language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
install:
  - pip install .
  - pip install coveralls
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then coverage run --source=configcontextualchecker -m unittest2 discover; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then coverage run --source=configcontextualchecker -m unittest discover; fi
after_success:
  coveralls
