language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install .
  - pip install coveralls
script:
  - coverage run --source=configcontextualchecker -m unittest discover
after_success:
  coveralls
